[v1]
"bat 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"broot 1.43.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["broot"]
"cargo-update 14.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"fre 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fre"]
"just 1.35.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"lscolors 0.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lscolors"]
"lsd 1.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["lsd"]
"navi 2.23.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["navi"]
"ripdrag 0.4.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["ripdrag"]
"ripgrep_all 0.10.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "rga",
    "rga-fzf",
    "rga-fzf-open",
    "rga-preproc",
]
"starship 1.20.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"yazi-cli 0.3.0 (git+https://github.com/sxyazi/yazi.git#22a4be1f3d84111b96ea832feaf274b6f8953f46)" = ["ya"]
"yazi-fm 0.3.0 (git+https://github.com/sxyazi/yazi.git#22a4be1f3d84111b96ea832feaf274b6f8953f46)" = ["yazi"]
"zoxide 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
